//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrigorificosBle.Almacen.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFinal
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public int Entradas { get; set; }
        public int Salidas { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
