//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrigorificosBle.Almacen.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linea
    {
        public Linea()
        {
            this.SubLineas = new HashSet<SubLinea>();
        }
    
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<SubLinea> SubLineas { get; set; }
    }
}
