//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrigorificosBle.Almacen.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public Orden()
        {
            this.OrdenItems = new HashSet<OrdenItem>();
            this.SalidaItems = new HashSet<SalidaItem>();
            this.SubOrdenes = new HashSet<SubOrden>();
        }
    
        public long Id { get; set; }
        public long Numero { get; set; }
        public string Tipo { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<long> IdOrdenBase { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string CentroCostos { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public double Descuento { get; set; }
        public bool Anulada { get; set; }
        public bool Cancelada { get; set; }
        public string Notas { get; set; }
    
        public virtual ICollection<OrdenItem> OrdenItems { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<SalidaItem> SalidaItems { get; set; }
        public virtual ICollection<SubOrden> SubOrdenes { get; set; }
    }
}
