//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrigorificosBle.Almacen.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubOrden
    {
        public long Id { get; set; }
        public long IdOrdenPadre { get; set; }
        public long IdOrden { get; set; }
    
        public virtual Orden Orden { get; set; }
        public virtual Orden OrdenPadre { get; set; }
    }
}
